### ISSUE TITLE
Create Landing Page

### ISSUE THREAD

**Issue by joedubill** [cse442-at-ub/cse442-semester-project-epstein#8]
Tests:
-Open home page (from index.html)
-Verify page renders showing text descriptions on the right side and image on the left side
-Verify clicking the link to login/sign up brings you to the login page
-Verify Resizing window maintains components' formatting on page, and making the window the minimum size crops out components as needed

**Comment by joeydubill** [comment]
Tests:
-Go to home page (render from index.html) and verify:
-Text and images show up with proper formatting
-Clicking the link to login/sign up brings you there (will be 404 until merge)
